[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
add_imports = [
    # PEP-563 (new semantics for annotations) is gated behind
    # 'from __future__ import annotations', including Python 3.10 & 3.11.
    # https://docs.python.org/3/library/__future__.html#id1
    "from __future__ import annotations",
]

[tool.mypy]
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "tweepy.*",  # https://github.com/tweepy/tweepy/pull/1828
]
ignore_missing_imports = true
